version: '3'
services:
  db:
    image: mongo
    command: mongod --smallfiles --quiet
    ports:
      - "27017:27017"
  back_end:
    build: ./back_end
    command: bash -c "rm -rf tmp/pids/server.pid && bundle install && rails db:drop && rails db:create && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back_end:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  front_end:
    build: ./front_end/door2door_front_end
    command: npm start
    volumes:
      - ./front_end/door2door_front_end:/app
    ports:
      - "3001:3001"
  simulator:
    build: ./driver-simulator
    command: sh -c "./wait-for-it.sh back_end:3000 -t 0 -- yarn install && yarn start back_end:3000"
    depends_on:
      - back_end
